//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugesto
    {
        public int Id { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public int EventoId { get; set; }
        public string Usuario_email { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
